# Settings for the app
app:
  # HTML Title
  title: re//VISION
  # Header name
  name: re//VISION
  # Meta description that will show up in Google search results
  meta_description: _(re//VISION – Better Block Grand Rapids. Envision the future of Grand Rapids.)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: true
  options:
    center:
      lat: 42.960423
      lng: -85.661704
    zoom: 16
    minZoom: 10
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  rain_garden:
    default: blue
    focused: red
    label: _(Rain Garden)
  green_street:
    default: blue
    focused: red
    label: _(Green Street)
  urban_garden:
    default: blue
    focused: red
    label: _(Urban Garden)
  bike_rental:
    default: blue
    focused: red
    label: _(Bike Rental)
  two_way_bike_lane:
    default: blue
    focused: red
    label: _(Two-way Bike Lanes)
  parklet:
    default: blue
    focused: red
    label: _(Bike Rental)
  food_truck_pod:
    default: blue
    focused: red
    label: _(Food Truck Pod)
  bouquinistes:
    default: blue
    focused: red
    label: _(Bouquinistes)
  work_yard:
    default: blue
    focused: red
    label: _(Work Yard)
  library:
    default: blue
    focused: red
    label: _(Bus Stop Library)


# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  blue:
    iconUrl: /static/css/images/feature-point.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Build Here!)
  action_text: _(built)
  title: _(Build a Better Grand Rapids)
  action_text: _(created)
  anonymous_name: _(A Grand Rapidian)
  submit_button_label: _(Build It!)
  items:
    - prompt: _(What do you want to build here?)
      type: select
      name: location_type
      options:
        - label: _(re//Purpose – Green Street)
          value: green_street
        - label: _(re//Seed – Urban Gardening)
          value: urban_garden
        - label: _(re//Cycle – Bike Rental)
          value: bike_rental
        - label: _(re//Configure – 2-way Bike Lanes)
          value: two_way_bike_lane
        - label: _(re//Define – Parklets)
          value: parklet
        - label: _(re//Fuel – Food Truck Pod)
          value: food_truck_pod
        - label: _(re//Gift – Bouquinistes)
          value: bouquiniste
        - label: _(re//Play – Work Yard)
          value: work_yard
        - label: _(re//Cover – Urban Tree Canopy)
          value: tree_canopy
        - label: _(re//Read – Bus Stop Library)
          value: library
    - prompt: _(Why Here?)
      type: textarea
      name: why_here
      attrs:
        - key: placeholder
          value: _(Why Here?)
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30


survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(A Grand Rapidian)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This)
  action_text: supported
  anonymous_name: _(A Grand Rapidian)

pages:
  - title: _(About)
    slug: about
    name: about
    start_page: true

  - title: _(re//PURPOSE)
    slug: repurpose
    name: repurpose

  - title: _(re//SEED)
    slug: reseed
    name: reseed

  - title: _(re//CYCLE)
    slug: recycle
    name: recycle

  - title: _(re//DEFINE)
    slug: redefine
    name: redefine

  - title: _(re//FUEL)
    slug: refuel
    name: refuel

  - title: _(re//GIFT)
    slug: regift
    name: regift

  - title: _(re//PLAY)
    slug: replay
    name: replay

  - title: _(re//COVER)
    slug: recover
    name: recover

  - title: _(re//READ)
    slug: reread
    name: reread

  - title: _(re//STATE)
    external: true
    url: http://betterblockgr.com
